### ISSUE TITLE
SSL certificate problem

### ISSUE THREAD

**Issue by carter3x** [jamiehollern/eventbrite#6]
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: self signed certificate in certificate chain (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in C:\xampp\htdocs\eventbrite\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 C:\xampp\htdocs\eventbrite\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 C:\xampp\htdocs\eventbrite\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 C:\xampp\htdocs\eventbrite\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 C:\xampp\htdocs\eventbrit in C:\xampp\htdocs\eventbrite\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187

**Comment by stephenwf** [comment]
See: http://docs.guzzlephp.org/en/latest/request-options.html?highlight=verify#verify

When calling makeRequest you can pass guzzle options
```php
$eventbrite->makeRequest(
    'GET', 
    'users/me/orders/', 
    ['expand' => 'event.venue'], 
    null, 
    null, 
    [ /* guzzle options here */ ]
);
```

As per docs in guzzle, passing:
```
['verify' => '/path/to/cert.pem']
```

Will allow you to use the self signed certificate.
