### ISSUE TITLE
POST - Can't update event. What am I missing?

### ISSUE THREAD

**Issue by joshbruce** [jamiehollern/eventbrite#7]
Sorry to ask what I'm sure should be relatively obvious...not able to post to an event. 

GET works famously, and I appreciate the simplicity of the solution.

The experiment is updating the capacity of an Event.

## Steps to recreate

1. Create a private, unpublished event in Eventbrite. 
2. Get the id.
3. Add some tickets to establish initial capacity (50).
3. Run: 

```php
// Instantiates the Eventbrite library
$eb = EventbriteClient::setAuthToken(env('OAUTH'), true);

// Gets the Event from Eventbrite
// $eb->get('events/:id')
$event = EventbriteEvent::find('XXXXXXX', $eb);
```

Try to change the capacity and post.

```php
$eb->post('event/:id/', ['event.capacity' => 40]);
```

Result should have capacity of 50.

I've spent the last couple of hours trying to figure it out, but can't. Having said that, Postman works like a charm; however, I cannot do it as raw JSON. Instead, I have to do it as a form post.

<img width="954" alt="screen shot 2017-04-16 at 1 55 22 pm" src="https://cloud.githubusercontent.com/assets/15252830/25073120/62cd44e6-22ad-11e7-88ff-745efbfe542c.png">
<img width="975" alt="screen shot 2017-04-16 at 1 55 49 pm" src="https://cloud.githubusercontent.com/assets/15252830/25073114/47f377a8-22ad-11e7-945e-e7a173312853.png">

Again, I'm pretty sure I'm missing something obvious, but I cannot figure out what. Thanks again.

**Comment by jamiehollern** [comment]
The code provided isn't from this project. There are no classes named `EventbriteClient` or `EventbriteEvent` in this library.
